import type { Metadata } from "next";
import { Poppins, Inter, Work_Sans } from "next/font/google";
import "./globals.css";
import { PageProvider } from "./contexts/PageContext";
import ClientLayout from "./ClientLayout";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["600", "700"],
	variable: "--font-poppins",
});

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "500"],
	variable: "--font-inter",
});

const workSans = Work_Sans({
	subsets: ["latin"],
	weight: ["400", "600"],
	variable: "--font-work-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={`${poppins.variable} ${inter.variable} ${workSans.variable}`}>
			<PageProvider>
				<ClientLayout>{children}</ClientLayout>
			</PageProvider>
		</html>
	);
}
