import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CubeSceneWrapper from "./components/CubeSceneWrapper";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} w-screen h-screen overflow-hidden`}>
				<div className="relative w-full h-full">
					<CubeSceneWrapper />
					<Navbar />
					<main className="mt-20 absolute inset-0 w-full h-full z-10 pointer-events-none">{children}</main>
				</div>
			</body>
		</html>
	);
}
