import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CubeSceneWrapper from "./CubeSceneWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<CubeSceneWrapper />
				<main className="absolute inset-0 w-full h-full z-10 overflow-hidden select-none pointer-events-none">
					{children}
				</main>
			</body>
		</html>
	);
}
